**PANDAS**

In [4]:
pip install pandas

Requirement already satisfied: pandas in c:\Users\USER\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\USER\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\USER\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\USER\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\USER\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd

In [6]:
f=[12,23,45,67,]
print(f)

[12, 23, 45, 67]

**Series

In [7]:
ds=pd.Series(f)
print(ds)

0    12
1    23
2    45
3    67
dtype: int64

**DATAFRAME:

In [8]:
data ={
    "name":["murtaza","aaqib","zeeshan"],
    "age":[22,23,22],
    "adress":["sogam","sogam","sogam"]
}
xy=pd.DataFrame(data)
xy

      name  age adress
0  murtaza   22  sogam
1    aaqib   23  sogam
2  zeeshan   22  sogam

In [9]:
import pandas as pd
data ={
    " players name":["murtaza","aaqib","zeeshan","saqib gucci","fasil","zubair","faian","danish",'abass',"rahil","shahid"],
    "jersey number":[13,11,6,67,7,5,8,3,1,12,56],
    "age":[22,22,22,18,25,19,21,21,22,23,20],
    "fees":[200,200,200,170,200,150,100,120,140,130,150],

}
df =pd.DataFrame(data)
df

    players name  jersey number  age  fees
0        murtaza             13   22   200
1          aaqib             11   22   200
2        zeeshan              6   22   200
3    saqib gucci             67   18   170
4          fasil              7   25   200
5         zubair              5   19   150
6          faian              8   21   100
7         danish              3   21   120
8          abass              1   22   140
9          rahil             12   23   130
10        shahid             56   20   150

In [10]:
data=pd.read_csv(r"C:\Users\USER\Downloads\DATA SETS\train.csv")
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [11]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [12]:
data.head(20)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C

In [13]:
data.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [14]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [15]:
data.shape

(891, 12)

**iloc is to get a particulat item from a dataset but purely works on index**

In [16]:
data.iloc[0,3]

'Braund, Mr. Owen Harris'

In [17]:
data.iloc[7,8]

'349909'

**loc gets an individual data from dataset it worked with index and column names**

In [18]:
data.loc[0,'Ticket']

'A/5 21171'

In [19]:
data.loc[5,'Fare']

np.float64(8.4583)

In [20]:
data.loc[5,'Name']

'Moran, Mr. James'

***AGREGATE FUNCTION***

In [21]:
data['Fare'].sum()

np.float64(28693.9493)

In [22]:
data['Age'].max()

np.float64(80.0)

In [23]:
data['Age'].min()

np.float64(0.42)

In [24]:
data['Age'].mean()

np.float64(29.69911764705882)

In [25]:
data['Age'].isnull().sum()

np.int64(177)

In [26]:
data['Age'].notnull().sum()

np.int64(714)

In [27]:
data['Fare'].mean()

np.float64(32.204207968574636)

In [28]:
data.sort_values(by='Age')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [29]:
data.sort_values(by='Age',ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [30]:
data.sort_values(by='Fare',ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
...,...,...,...,...,...,...,...,...,...,...,...,...
806,807,0,1,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0000,B102,S
466,467,0,2,"Campbell, Mr. William",male,NaN,0,0,239853,0.0000,NaN,S
481,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0000,NaN,S
822,823,0,1,"Reuchlin, Jonkheer. John George",male,38.0,0,0,19972,0.0000,NaN,S

In [31]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [32]:
data.sort_values(by='Age', inplace=True)
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [33]:
data['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [34]:
data['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [35]:
data['Survived'].value_counts()

Survived
0    549
1    342
Name: count, dtype: int64

In [36]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,1,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S

In [37]:
data['Survived']=data['Survived'].map({0:'Alive',1:'Dead'})
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,Dead,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,Dead,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,Dead,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,Dead,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,Dead,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S

**DATA MANIPULATION:---**
Sorting,
Filteration,
Searching

In [38]:
data[data['Age']>18]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
291,292,Dead,1,"Bishop, Mrs. Dickinson H (Helen Walton)",female,19.0,1,0,11967,91.0792,B49,C
566,567,Alive,3,"Stoytcheff, Mr. Ilia",male,19.0,0,0,349205,7.8958,NaN,S
546,547,Dead,2,"Beane, Mrs. Edward (Ethel Clarke)",female,19.0,1,0,2908,26.0000,NaN,S
283,284,Dead,3,"Dorking, Mr. Edward Arthur",male,19.0,0,0,A/5. 10482,8.0500,NaN,S
302,303,Alive,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
116,117,Alive,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,Alive,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,Alive,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
851,852,Alive,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
630,631,Dead,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S

In [39]:
data[
    (data['Age']>18)&
    (data['Sex']=='male')
]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
566,567,Alive,3,"Stoytcheff, Mr. Ilia",male,19.0,0,0,349205,7.8958,NaN,S
283,284,Dead,3,"Dorking, Mr. Edward Arthur",male,19.0,0,0,A/5. 10482,8.0500,NaN,S
302,303,Alive,3,"Johnson, Mr. William Cahoone Jr",male,19.0,0,0,LINE,0.0000,NaN,S
748,749,Alive,1,"Marvin, Mr. Daniel Warner",male,19.0,1,0,113773,53.1000,D30,S
372,373,Alive,3,"Beavan, Mr. William Thomas",male,19.0,0,0,323951,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
116,117,Alive,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,Alive,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,Alive,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
851,852,Alive,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
630,631,Dead,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S

In [40]:
alive_female_children=data[
    (data['Age']<18)&
    (data['Survived']==0)&
    (data['Sex']=='female')
]
alive_female_children

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [41]:
alive_female_children.shape

(0, 12)

In [42]:
Pclass_age_male=data[
    (data['Pclass']==3)&
    (data['Age']>10)&
    (data['Sex']=='male')
]
Pclass_age_male

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
59,60,Alive,3,"Goodwin, Master. William Frederick",male,11.0,5,2,CA 2144,46.9000,NaN,S
731,732,Alive,3,"Hassan, Mr. Houssein G N",male,11.0,0,0,2699,18.7875,NaN,C
125,126,Dead,3,"Nicola-Yarred, Master. Elias",male,12.0,1,0,2651,11.2417,NaN,C
683,684,Alive,3,"Goodwin, Mr. Charles Edward",male,14.0,5,2,CA 2144,46.9000,NaN,S
686,687,Alive,3,"Panula, Mr. Jaako Arnold",male,14.0,4,1,3101295,39.6875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
94,95,Alive,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
326,327,Alive,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
280,281,Alive,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
116,117,Alive,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
851,852,Alive,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S

In [43]:
fare_age=data[
    (data['Fare']>5)&
    (data['Age']>70)
]
fare_age

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
116,117,Alive,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
493,494,Alive,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,Alive,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
851,852,Alive,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
630,631,Dead,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S

In [44]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,Dead,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C
755,756,Dead,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,Dead,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,Dead,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,Dead,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S

In [45]:
data[data['Name'].str.contains('Braund')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,Alive,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
477,478,Alive,3,"Braund, Mr. Lewis Richard",male,29.0,1,0,3460,7.0458,NaN,S

In [46]:
data[data['Name'].str.contains('Miss')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
644,645,Dead,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,Dead,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
172,173,Dead,3,"Johnson, Miss. Eleanor Ileen",female,1.00,1,1,347742,11.1333,NaN,S
381,382,Dead,3,"Nakid, Miss. Maria (""Mary"")",female,1.00,0,2,2653,15.7417,NaN,C
642,643,Alive,3,"Skoog, Miss. Margit Elizabeth",female,2.00,3,2,347088,27.9000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
697,698,Dead,3,"Mullens, Miss. Katherine ""Katie""",female,NaN,0,0,35852,7.7333,NaN,Q
727,728,Dead,3,"Mannion, Miss. Margareth",female,NaN,0,0,36866,7.7375,NaN,Q
792,793,Alive,3,"Sage, Miss. Stella Anna",female,NaN,8,2,CA. 2343,69.5500,NaN,S
863,864,Alive,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
888,889,Alive,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [47]:
data[data['Name'].str.contains('Duran')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
866,867,Dead,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C

In [48]:
data[data['Ticket'].str.contains('SC/PARIS 2149')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
866,867,Dead,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C

In [49]:
data.iloc[0,3]='murtaza'
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,Dead,3,murtaza,male,0.42,0,1,2625,8.5167,NaN,C
755,756,Dead,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,Dead,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,Dead,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,Dead,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S

In [50]:
data.replace('Allen, Mr. William Henry','murtaza mir',inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,Dead,3,murtaza,male,0.42,0,1,2625,8.5167,NaN,C
755,756,Dead,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,Dead,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,Dead,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,Dead,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,Alive,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,Alive,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,Alive,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,Alive,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,Alive,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

In [51]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,Dead,3,murtaza,male,0.42,0,1,2625,8.5167,NaN,C
755,756,Dead,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,Dead,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,Dead,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,Dead,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S

In [52]:
data[data['Sex'].isin(['male'])]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,Dead,3,murtaza,male,0.42,0,1,2625,8.5167,NaN,C
755,756,Dead,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
78,79,Dead,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
831,832,Dead,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
305,306,Dead,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
...,...,...,...,...,...,...,...,...,...,...,...,...
839,840,Dead,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
846,847,Alive,3,"Sage, Mr. Douglas Bullen",male,NaN,8,2,CA. 2343,69.5500,NaN,S
859,860,Alive,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
868,869,Alive,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,Alive,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S

In [53]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,Dead,3,murtaza,male,0.42,0,1,2625,8.5167,NaN,C
755,756,Dead,2,"Hamalainen, Master. Viljo",male,0.67,1,1,250649,14.5000,NaN,S
644,645,Dead,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
469,470,Dead,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
78,79,Dead,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S

In [54]:
data.groupby('Sex')['Survived'].sum()

Sex
female    DeadDeadDeadDeadAliveAliveDeadAliveAliveDeadAl...
male      DeadDeadDeadDeadDeadAliveDeadAliveDeadDeadAliv...
Name: Survived, dtype: str

In [55]:
data['Sex']=data['Sex'].map({'male':0,'female':1})

In [56]:
data.groupby('Survived')['Sex'].sum()

Survived
Alive     81
Dead     233
Name: Sex, dtype: int64

In [57]:
data['Survived']=data['Survived'].map({1:0,0:1})

In [58]:
data.groupby('Sex')['Survived'].sum()

Sex
0    0.0
1    0.0
Name: Survived, dtype: float64

In [59]:
data.groupby('Pclass')['Survived'].sum()

Pclass
1    0.0
2    0.0
3    0.0
Name: Survived, dtype: float64

In [60]:
data.groupby('Sex')['Survived'].mean()

Sex
0   NaN
1   NaN
Name: Survived, dtype: float64

In [61]:
data['Sex']=data['Sex'].map({'female':0,'male':1})

In [62]:
data.groupby('Survived')['Sex'].sum()

Series([], Name: Sex, dtype: float64)

In [63]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,NaN,3,murtaza,NaN,0.42,0,1,2625,8.5167,NaN,C
755,756,NaN,2,"Hamalainen, Master. Viljo",NaN,0.67,1,1,250649,14.5000,NaN,S
644,645,NaN,3,"Baclini, Miss. Eugenie",NaN,0.75,2,1,2666,19.2583,NaN,C
469,470,NaN,3,"Baclini, Miss. Helene Barbara",NaN,0.75,2,1,2666,19.2583,NaN,C
78,79,NaN,2,"Caldwell, Master. Alden Gates",NaN,0.83,0,2,248738,29.0000,NaN,S

In [64]:
data['Survived'].value_counts()

Series([], Name: count, dtype: int64)

In [65]:
data['Age'].isnull().sum()

np.int64(177)

In [66]:
data['Age'].mean()

np.float64(29.69911764705882)

In [67]:
data.dropna(subset='Age')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,NaN,3,murtaza,NaN,0.42,0,1,2625,8.5167,NaN,C
755,756,NaN,2,"Hamalainen, Master. Viljo",NaN,0.67,1,1,250649,14.5000,NaN,S
644,645,NaN,3,"Baclini, Miss. Eugenie",NaN,0.75,2,1,2666,19.2583,NaN,C
469,470,NaN,3,"Baclini, Miss. Helene Barbara",NaN,0.75,2,1,2666,19.2583,NaN,C
78,79,NaN,2,"Caldwell, Master. Alden Gates",NaN,0.83,0,2,248738,29.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
116,117,NaN,3,"Connors, Mr. Patrick",NaN,70.50,0,0,370369,7.7500,NaN,Q
493,494,NaN,1,"Artagaveytia, Mr. Ramon",NaN,71.00,0,0,PC 17609,49.5042,NaN,C
96,97,NaN,1,"Goldschmidt, Mr. George B",NaN,71.00,0,0,PC 17754,34.6542,A5,C
851,852,NaN,3,"Svensson, Mr. Johan",NaN,74.00,0,0,347060,7.7750,NaN,S
630,631,NaN,1,"Barkworth, Mr. Algernon Henry Wilson",NaN,80.00,0,0,27042,30.0000,A23,S

In [68]:
data['Age']=data['Age'].fillna(data['Age'].mean())

In [69]:
data['Age'].isnull().sum()

np.int64(0)

In [70]:
female_alive_children=data[
    (data['Age']<18)&
    (data['Sex']=='female')&
    (data['Survived']==1)

]

In [71]:
female_alive_children.to_csv('children.csv')

In [72]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\Users\USER\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\Users\USER\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [73]:
female_alive_children.to_excel('children.xlsx')

In [80]:
children =pd.read_excel("children.xlsx")